export const sourceRegistry = [
  {
    id: 'nfsc-criminal-mirror',
    name: 'NFSC Criminal Court Documents Mirror',
    shortName: 'NFSC 镜像',
    type: 'Mirror',
    confidence: 'medium',
    adapter: 'nfscCriminalMirror',
    url: 'https://nfsc.press/2024/08/25/criminal-court-case-documents-123-cr-00118-at/',
    coverage: 'S.D.N.Y. 1:23-cr-00118-AT criminal docket PDFs mirrored from public filings.',
    limitations: 'Not the court docket of record. Treat as a PDF mirror and verify critical items against PACER/RECAP.',
    enabled: true,
  },
  {
    id: 'doj-victim-page',
    name: 'U.S. Attorney SDNY Victim Information Page',
    shortName: 'DOJ 受害者页',
    type: 'Official Agency',
    confidence: 'high',
    adapter: 'dojVictimPage',
    url: 'https://www.justice.gov/usao-sdny/united-states-v-ho-wan-kwok-aka-miles-guo-and-kin-ming-je-aka-william-je',
    coverage: 'Official DOJ victim updates for United States v. Ho Wan Kwok, Kin Ming Je, and Yanping Wang.',
    limitations: 'Agency page, not a complete court docket.',
    enabled: true,
  },
  {
    id: 'doj-sentencing-release',
    name: 'DOJ Sentencing Press Release',
    shortName: 'DOJ 判刑稿',
    type: 'Official Agency',
    confidence: 'high',
    adapter: 'dojSentencingRelease',
    url: 'https://www.justice.gov/usao-sdny/pr/miles-guo-sentenced-30-years-prison-leading-billion-dollar-fraud',
    coverage: 'Official DOJ announcement of Miles Guo sentencing.',
    limitations: 'May be protected by anti-bot interstitials; facts should still be cross-checked against judgment and transcript.',
    enabled: true,
  },
  {
    id: 'sec-press-2023-50',
    name: 'SEC Press Release 2023-50',
    shortName: 'SEC 起诉稿',
    type: 'Official Agency',
    confidence: 'high',
    adapter: 'secPressRelease',
    url: 'https://www.sec.gov/newsroom/press-releases/2023-50',
    coverage: 'SEC civil enforcement announcement against Miles Guo and William Je.',
    limitations: 'Agency allegations and civil-enforcement framing; not a full civil docket.',
    enabled: true,
  },
  {
    id: 'gtv-fair-fund',
    name: 'GTV Media Group Fair Fund',
    shortName: 'GTV Fair Fund',
    type: 'Claims Agent',
    confidence: 'high',
    adapter: 'gtvFairFund',
    url: 'https://www.gtvmediagroupfairfund.com/',
    coverage: 'SEC Fair Fund distribution status for GTV Media Group, Saraca Media Group, and Voice of Guo Media.',
    limitations: 'Claims-administration site. Distribution mechanics can lag court and SEC enforcement events.',
    enabled: true,
  },
  {
    id: 'himalaya-restoration',
    name: 'Himalaya Restoration Public Project Site',
    shortName: 'Himalaya Restoration',
    type: 'Party / Counsel Project Site',
    confidence: 'medium',
    adapter: 'himalayaRestoration',
    url: 'https://himalayarestoration.org/',
    coverage: 'Current public project pages, legal updates, affidavit-template references, and court-file links concerning Himalaya Exchange customers.',
    limitations: 'This is a party/counsel project site, not a court docket. Its descriptions and customer counts are advocacy-side statements unless confirmed by PACER, RECAP, or court orders.',
    enabled: true,
  },
  {
    id: 'himalaya-restoration-archive',
    name: 'Himalaya Restoration Historical Public Archive',
    shortName: 'Himalaya 历史存档',
    type: 'Historical Web Archive',
    confidence: 'medium',
    adapter: 'himalayaRestorationArchive',
    url: 'https://web.archive.org/web/*/https://himalayarestoration.com/',
    coverage: 'Internet Archive snapshots of the 2023-2025 Himalaya Restoration site, including previously public court-document collections and legal updates.',
    limitations: 'Historical snapshots prove what the site published at a captured time; they do not prove that a filing was accepted, adjudicated, or complete on the official docket.',
    enabled: true,
  },
  {
    id: 'epiq-kwok-trustee',
    name: 'Epiq 11 Kwok Trustee Docket',
    shortName: 'Epiq 破产案',
    type: 'Claims Agent',
    confidence: 'high',
    adapter: 'epiqKwokDocket',
    url: 'https://dm.epiq11.com/case/kwoktrustee/dockets',
    coverage: 'D. Conn. bankruptcy docket and trustee case material for In re Ho Wan Kwok.',
    limitations: 'Modern JavaScript app. Static HTML check is available now; full docket extraction needs the Epiq JSON endpoint.',
    enabled: true,
  },
  {
    id: 'courtlistener-recap',
    name: 'CourtListener / RECAP',
    shortName: 'RECAP',
    type: 'CourtListener / RECAP',
    confidence: 'high',
    adapter: 'courtlistenerRecap',
    url: 'https://www.courtlistener.com/',
    coverage: 'RECAP docket and PDF metadata when mirrored by PACER users.',
    limitations: 'Public Atom feeds provide recent docket metadata without a token. A token adds REST pagination, descriptions, and available-PDF discovery; PACER remains the docket of record.',
    enabled: true,
  },
  {
    id: 'pacer',
    name: 'PACER',
    shortName: 'PACER',
    type: 'Official Court',
    confidence: 'highest',
    adapter: 'pacerPlaceholder',
    url: 'https://pacer.uscourts.gov/',
    coverage: 'Docket of record for federal district, bankruptcy, and appellate courts.',
    limitations: 'Requires PACER credentials and fee-aware access controls.',
    enabled: true,
  },
  {
    id: 'federal-register-policy',
    name: 'Federal Register Policy Search',
    shortName: '政策雷达',
    type: 'Official Agency',
    confidence: 'high',
    adapter: 'federalRegisterPolicy',
    url: 'https://www.federalregister.gov/',
    coverage: 'Policy and regulatory changes affecting forfeiture, securities enforcement, bankruptcy, and sanctions context.',
    limitations: 'Topic-level policy monitor; not case-specific proof unless a document directly references the matter.',
    enabled: true,
  },
]

const withdrawalProceedings = Array.from({ length: 8 }, (_, index) => {
  const sequence = 42 + index
  const docket = `3:26-mc-${String(sequence).padStart(5, '0')}`
  return {
    id: `dconn-26-mc-${String(sequence).padStart(5, '0')}`,
    title: `In Re: Ho Wan Kwok, withdrawal-of-reference proceeding ${docket}`,
    shortTitle: `Withdrawal ${docket}`,
    court: 'D. Conn.',
    docket,
    kind: 'Bankruptcy / District Court',
    status: 'Independently tracked withdrawal-of-reference proceeding',
    priority: 'high',
    lastKnownFiling: 'Requires live docket refresh',
    stage: 'District-court proceeding concerning withdrawal of the reference from the bankruptcy court; each miscellaneous docket is audited separately.',
    focus: 'Withdrawal-of-reference briefing, party positions, assignment, disposition, and the effect on the underlying trustee litigation.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Which underlying adversary proceeding and parties are assigned to this miscellaneous docket.', 'Whether the district court grants, denies, consolidates, transfers, or administratively closes the request.'],
  }
})

export const cases = [
  {
    id: 'sdny-23-cr-118',
    title: 'United States v. Ho Wan Kwok, a/k/a Miles Guo, et al.',
    shortTitle: '刑事主案',
    court: 'S.D.N.Y.',
    docket: '1:23-cr-00118-AT',
    kind: 'Criminal',
    status: 'Post-judgment appeal and forfeiture ancillary proceedings',
    priority: 'critical',
    lastKnownFiling: 'Doc 868, 2026-08-06',
    stage: 'Judgment entered; notice of appeal filed; forfeiture claims and mandamus activity remain active.',
    focus: 'Conviction, 360-month sentence, $889M forfeiture judgment, third-party § 853(n) claims, Second Circuit appeal.',
    sourceIds: ['nfsc-criminal-mirror', 'doj-victim-page', 'pacer', 'courtlistener-recap'],
    watchQuestions: [
      'Second Circuit direct appeal 26-1853 briefing schedule, counsel appearances, transcript status, and issue-preservation filings.',
      'Whether SDNY dockets and considers third-party ancillary forfeiture petitions after the mandamus denials without prejudice.',
      'Any revised preliminary/final forfeiture orders, remission process notices, or asset-specific claims.',
    ],
  },
  {
    id: 'ca2-26-1853',
    title: 'United States of America v. Guo',
    shortTitle: 'Criminal Direct Appeal',
    court: 'Second Circuit',
    docket: '26-1853',
    kind: 'Criminal Appeal',
    status: 'Direct appeal opened; counsel and transcript filings underway',
    priority: 'critical',
    lastKnownFiling: 'Docket entry 17, 2026-08-06',
    stage: 'The direct criminal appeal from the July 2, 2026 judgment is pending in the Second Circuit.',
    focus: 'Counsel status, transcript record, briefing schedule, preserved trial and sentencing issues, conviction, sentence, and forfeiture judgment.',
    sourceIds: ['courtlistener-recap', 'pacer'],
    watchQuestions: [
      'Whether counsel substitution is granted and which lawyers remain counsel of record.',
      'When the transcript record and scheduling order become complete, and when the opening brief is due.',
      'Which conviction, evidentiary, sentencing, loss, and forfeiture issues are preserved in the merits briefs.',
    ],
  },
  {
    id: 'sdny-23-cv-2200',
    title: 'SEC v. Kwok, Je, and related GTV entities',
    shortTitle: 'SEC 民事案',
    court: 'S.D.N.Y.',
    docket: '1:23-cv-02200',
    kind: 'Civil Enforcement',
    status: 'SEC civil enforcement line tied to GTV and digital-asset offerings',
    priority: 'high',
    lastKnownFiling: 'Needs live docket refresh',
    stage: 'Civil enforcement claims and asset recovery must be reconciled with criminal forfeiture and Fair Fund credits.',
    focus: 'Securities fraud allegations, disgorgement offsets, investor distribution, overlap with criminal forfeiture loss calculations.',
    sourceIds: ['sec-press-2023-50', 'gtv-fair-fund', 'pacer', 'courtlistener-recap'],
    watchQuestions: [
      'Whether civil disgorgement or Fair Fund payments reduce criminal forfeiture exposure.',
      'Status of claims against Kin Ming Je / William Je and entity defendants.',
      'Any stay, consent judgment, default, or parallel receivership activity.',
    ],
  },
  {
    id: 'sec-admin-3-20537',
    title: 'In the Matter of GTV Media Group, Saraca Media Group, and Voice of Guo Media',
    shortTitle: 'GTV Fair Fund',
    court: 'SEC Administrative Proceeding',
    docket: 'Admin. Proc. File No. 3-20537',
    kind: 'Administrative / Fair Fund',
    status: 'Distribution administration ongoing',
    priority: 'high',
    lastKnownFiling: 'Fair Fund site reports second tranche commenced 2023-09-29',
    stage: 'Investor compensation line that intersects with criminal forfeiture and restitution/remission analysis.',
    focus: 'Fair Fund paid amount, claimant eligibility, tranche timing, offset against criminal forfeiture.',
    sourceIds: ['gtv-fair-fund', 'sec-press-2023-50'],
    watchQuestions: [
      'Whether additional distributions or administrator notices change loss and remission calculations.',
      'How claimants who received Fair Fund payments are treated in criminal forfeiture remission.',
    ],
  },
  {
    id: 'dconn-22-50073',
    title: 'In re Ho Wan Kwok',
    shortTitle: '康州破产案',
    court: 'D. Conn. Bankruptcy Court',
    docket: '22-50073',
    kind: 'Bankruptcy',
    status: 'Trustee asset recovery and claim administration',
    priority: 'critical',
    lastKnownFiling: 'Needs Epiq live docket extraction',
    stage: 'Bankruptcy estate, trustee litigation, asset ownership, and claims may affect criminal forfeiture collection.',
    focus: 'Estate assets, alter ego findings, Lady May / HK International line, creditor claims, trustee motions.',
    sourceIds: ['epiq-kwok-trustee', 'pacer', 'courtlistener-recap'],
    watchQuestions: [
      'Latest trustee docket entries and any appeals from turnover, alter ego, or sale orders.',
      'Whether criminal forfeiture, SEC disgorgement, and bankruptcy estate claims conflict or coordinate.',
      'Any family, trust, foundation, or nominee-ownership assertions tied to recoverable assets.',
    ],
  },
  {
    id: 'ca2-24-2504',
    title: 'In re Kwok, HK International Funds Investments / Lady May line',
    shortTitle: '第二巡回资产案',
    court: 'Second Circuit',
    docket: '24-2504',
    kind: 'Appellate / Bankruptcy',
    status: 'Published 2026 appellate ruling reported at 172 F.4th 145',
    priority: 'high',
    lastKnownFiling: 'Opinion reported 2026-04-06',
    stage: 'Alter ego and estate-property ruling informs the asset map.',
    focus: 'Whether assets nominally held through HK International or related entities belong to the bankruptcy estate.',
    sourceIds: ['courtlistener-recap', 'epiq-kwok-trustee'],
    watchQuestions: [
      'Any petition for rehearing, mandate, Supreme Court petition, or follow-on bankruptcy enforcement filings.',
      'Which family, trust, or investment vehicles are named in the operative record.',
    ],
  },
  {
    id: 'bkd-22-05032',
    title: 'Pacific Alliance Asia Opportunity Fund L.P. v. Kwok',
    shortTitle: 'Bankruptcy Adversary Proceeding',
    court: 'D. Conn. Bankruptcy Court',
    docket: '22-05032',
    kind: 'Bankruptcy Adversary',
    status: 'Related adversary proceeding within the Kwok bankruptcy line',
    priority: 'high',
    lastKnownFiling: 'RECAP entry 214, 2024-10-01',
    stage: 'This adversary proceeding must be read under the 22-50073 bankruptcy mother case and related district-court review.',
    focus: 'Creditor claims, estate ownership, turnover or alter-ego issues, and any district-court review of bankruptcy rulings.',
    sourceIds: ['courtlistener-recap', 'epiq-kwok-trustee', 'pacer'],
    watchQuestions: [
      'Whether later filings appear in the bankruptcy docket, district court, or an appellate docket under a different caption.',
      'Which rulings remain operative after district-court review and how they affect estate-property analysis.',
    ],
  },
  {
    id: 'dconn-26-withdrawal-reference',
    title: 'In Re: Ho Wan Kwok, 2026 Withdrawal-of-Reference Proceedings',
    shortTitle: '2026 Withdrawal Proceedings',
    court: 'D. Conn.',
    docket: '3:26-mc-00042 through 3:26-mc-00049',
    kind: 'Bankruptcy / District Court',
    status: 'Eight related withdrawal-of-reference proceedings',
    priority: 'high',
    lastKnownFiling: 'Public RECAP feeds updated through 2026-07-28',
    stage: 'Eight district-court miscellaneous cases seek or address withdrawal of the bankruptcy reference; each keeps a separate docket while sharing the bankruptcy mother case.',
    focus: 'Withdrawal standards, jury-trial or forum arguments, objections, related-case management, and effects on trustee litigation involving Phillips Nizer, Putnam\'s Landscaping, SGB Packaging, and other parties.',
    sourceIds: ['courtlistener-recap', 'pacer'],
    watchQuestions: [
      'Which withdrawal motions are granted, denied, transferred, consolidated, or administratively closed.',
      'Whether merits proceedings remain in bankruptcy court or move to the district court in each numbered matter.',
      'How rulings in the eight matters affect the trustee\'s asset-recovery and professional-liability litigation.',
    ],
  },
  ...withdrawalProceedings,
  {
    id: 'edny-26-mc-2795',
    title: 'In re Application of Rui Hao under 28 U.S.C. § 1782',
    shortTitle: 'Section 1782 Related Proceeding',
    court: 'E.D.N.Y.',
    docket: '1:26-mc-02795',
    kind: 'Foreign-Proceeding Discovery',
    status: 'Discovery assistance proceeding related to a foreign matter',
    priority: 'medium',
    lastKnownFiling: 'Public RECAP feed updated through 2026-08-03',
    stage: 'The court granted Section 1782 discovery assistance on July 9, 2026; later compliance or challenge filings require docket verification.',
    focus: 'Scope of authorized discovery, subpoena target and compliance, foreign-proceeding use, and any motion to quash or modify.',
    sourceIds: ['courtlistener-recap', 'pacer'],
    watchQuestions: [
      'What discovery was authorized, who must respond, and whether any subpoena or production is contested.',
      'How the foreign proceeding relates to Kwok without treating the application allegations as adjudicated facts.',
    ],
  },
  {
    id: 'ca2-26-563-dx',
    title: 'In re DX, arising from United States v. Ho Wan Kwok',
    shortTitle: 'In re DX proceeding',
    court: 'Second Circuit',
    docket: '26-563',
    kind: 'Appellate / Ancillary Proceeding',
    status: 'Related Second Circuit proceeding with public filings and mandate activity',
    priority: 'high',
    lastKnownFiling: 'Public RECAP feed observed through 2026-08-06',
    stage: 'Ancillary appellate record-development and freezing/non-completion issues arising from the criminal matter.',
    focus: 'Appellate record development, third-party or pro se requests, and the relationship to the criminal docket.',
    sourceIds: ['courtlistener-recap', 'pacer'],
    watchQuestions: [
      'What relief was requested, and which orders or mandates resolved each request.',
      'Whether public and sealed versions of the record differ in material ways.',
    ],
  },
  {
    id: 'bkd-24-05021-bannon',
    title: 'Despins v. Bannon Strategic Advisors, Inc.',
    shortTitle: 'Bannon Strategic Advisors adversary case',
    court: 'D. Conn. Bankruptcy Court',
    docket: '24-05021',
    kind: 'Bankruptcy Adversary',
    status: 'Trustee adversary proceeding under jointly administered Ho Wan Kwok bankruptcy cases',
    priority: 'high',
    lastKnownFiling: 'Public RECAP feed observed through 2026-08-03',
    stage: 'Trustee litigation connected to the 22-50073 estate; read alongside the mother case and any withdrawal proceedings.',
    focus: 'Trustee claims, defenses, discovery, settlement, and asset-recovery implications.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Whether later orders, judgments, settlements, or appeals affect estate recovery.', 'Which allegations are pleadings and which have been adjudicated.'],
  },
  {
    id: 'bkd-24-05249-aca',
    title: 'Despins, Luc A., Chapter 11 Trustee v. ACA Capital Group Ltd.',
    shortTitle: 'ACA Capital trustee case',
    court: 'D. Conn. Bankruptcy Court',
    docket: '24-05249',
    kind: 'Bankruptcy Adversary',
    status: 'Trustee adversary proceeding tied to the Ho Wan Kwok estate',
    priority: 'high',
    lastKnownFiling: 'Public RECAP feed observed through 2026-08-12',
    stage: 'Active trustee litigation; document-level claims and defenses require docket and PDF review.',
    focus: 'Estate recovery, counterclaims, discovery, and any disposition affecting creditors.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Latest dispositive motions, hearings, and judgments.', 'Whether any filing identifies additional asset or entity lines.'],
  },
  {
    id: 'bkd-24-05246-wa-hf',
    title: 'Despins, Luc A., Chapter 11 Trustee v. WA & HF LLC',
    shortTitle: 'WA & HF trustee case',
    court: 'D. Conn. Bankruptcy Court',
    docket: '24-05246',
    kind: 'Bankruptcy Adversary',
    status: 'Trustee adversary proceeding tied to the Ho Wan Kwok estate',
    priority: 'high',
    lastKnownFiling: 'Public RECAP feed observed through 2026-05-21',
    stage: 'Related estate-recovery proceeding; caption and mother-case references require ongoing verification.',
    focus: 'Trustee claims, ownership, defenses, and estate-property recovery.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['What claims and defenses are currently operative.', 'Whether any order changes the estate asset map.'],
  },
  {
    id: 'bkd-24-05006-aws',
    title: 'Despins v. Amazon Web Services, Inc.',
    shortTitle: 'Amazon Web Services trustee case',
    court: 'D. Conn. Bankruptcy Court',
    docket: '24-05006',
    kind: 'Bankruptcy Adversary',
    status: 'Trustee adversary proceeding tied to the Ho Wan Kwok estate',
    priority: 'medium',
    lastKnownFiling: 'Public RECAP feed observed through 2026-07-08',
    stage: 'Related trustee litigation; public feed confirms entries but does not establish complete document coverage.',
    focus: 'Trustee claims, defenses, discovery, and possible recovery for the estate.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Latest substantive orders and any resolution.', 'Whether the record contains material facts about entities or assets.'],
  },
  {
    id: 'bkd-24-05057-amazon',
    title: 'Despins v. Amazon.com, Inc.',
    shortTitle: 'Amazon.com trustee case',
    court: 'D. Conn. Bankruptcy Court',
    docket: '24-05057',
    kind: 'Bankruptcy Adversary',
    status: 'Trustee adversary proceeding tied to the Ho Wan Kwok estate',
    priority: 'medium',
    lastKnownFiling: 'Public RECAP feed observed through 2026-08-06',
    stage: 'Related trustee litigation; public feed confirms entries and some docket text only.',
    focus: 'Trustee claims, defenses, discovery, and possible recovery for the estate.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Latest substantive orders and any resolution.', 'Whether the record contains material facts about entities or assets.'],
  },
  {
    id: 'bkd-hk-int-despins',
    title: 'HK International Funds Investments (USA) Limited v. Despins',
    shortTitle: 'HK International v. Despins',
    court: 'D. Conn. Bankruptcy Court',
    docket: '22-05003',
    kind: 'Bankruptcy Adversary',
    status: 'Caption and docket number confirmed in the public CourtListener search record; official PACER header still preferred',
    priority: 'high',
    lastKnownFiling: 'Public RECAP feed observed through 2026-05-21',
    stage: 'Related to the estate and asset-ownership line; the public search record identifies this proceeding as 22-05003.',
    focus: 'HK International ownership position, trustee response, and effect on estate-property analysis.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Identify the currently operative claims, orders, and appeals.', 'Reconcile the asset-ownership rulings with the bankruptcy mother case and Second Circuit record.'],
  },
  {
    id: 'bkd-24-05275-lamp',
    title: 'Despins v. Lamp Capital LLC',
    shortTitle: 'Lamp Capital trustee case',
    court: 'D. Conn. Bankruptcy Court',
    docket: '24-05275',
    kind: 'Bankruptcy Adversary',
    status: 'Caption and docket number confirmed in the public CourtListener search record',
    priority: 'high',
    lastKnownFiling: 'Requires live docket refresh',
    stage: 'Chapter 11 trustee adversary proceeding connected to the Ho Wan Kwok estate and related entity defendants.',
    focus: 'Trustee claims, entity relationships, estate recovery, and any asset-ownership rulings involving Lamp Capital and named related entities.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Retrieve the operative complaint, answers, dispositive motions, and orders.', 'Map each named entity and asset allegation to evidence in the filed record.'],
  },
  {
    id: 'bkd-25-05088-1stdibs',
    title: 'Despins v. 1stdibs.com Inc.',
    shortTitle: '1stdibs trustee case',
    court: 'D. Conn. Bankruptcy Court',
    docket: '25-05088',
    kind: 'Bankruptcy Adversary',
    status: 'Caption-confirmed trustee adversary proceeding linked to the Ho Wan Kwok estate',
    priority: 'medium',
    lastKnownFiling: 'Public RECAP feed observed through 2025-08-15',
    stage: 'Older public entry discovered by name-variant search; live status requires a fresh docket check.',
    focus: 'Trustee claims and any connection to estate property or recovery.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Confirm whether the proceeding remains active, resolved, or administratively closed.', 'Retrieve public PDFs or docket text where available.'],
  },
  {
    id: 'bkd-25-05094-ny-blinds',
    title: 'Despins v. NY Blinds and Shades Inc. d/b/a Innovation Shades',
    shortTitle: 'NY Blinds trustee case',
    court: 'D. Conn. Bankruptcy Court',
    docket: '25-05094',
    kind: 'Bankruptcy Adversary',
    status: 'Caption-confirmed trustee adversary proceeding linked to the Ho Wan Kwok estate',
    priority: 'medium',
    lastKnownFiling: 'Public RECAP feed observed through 2025-08-15',
    stage: 'Older public entry discovered by name-variant search; live status requires a fresh docket check.',
    focus: 'Trustee claims and any connection to estate property or recovery.',
    sourceIds: ['courtlistener-recap', 'pacer', 'epiq-kwok-trustee'],
    watchQuestions: ['Confirm whether the proceeding remains active, resolved, or administratively closed.', 'Retrieve public PDFs or docket text where available.'],
  },
  {
    id: 'az-voice-of-guo',
    title: 'Zhang v. Voice of Guo Media Incorporated',
    shortTitle: 'Voice of Guo Arizona case',
    court: 'D. Ariz.',
    docket: '2:21-cv-01079',
    kind: 'Civil / Entity-Related',
    status: 'Caption, docket number, parties, and filing date confirmed in the public CourtListener search record',
    priority: 'medium',
    lastKnownFiling: 'Public RECAP feed observed through 2026-05-01',
    stage: 'The caption names Voice of Guo Media; relevance to the broader case portfolio must be confirmed from parties and pleadings.',
    focus: 'Entity status, claims, defenses, and any relationship to G-series or Fair Fund matters.',
    sourceIds: ['courtlistener-recap', 'pacer'],
    watchQuestions: ['Retrieve the operative pleadings and disposition documents.', 'Classify each claim and party relationship after reading the filings.'],
  },
  {
    id: 'related-people-companies',
    title: 'Related People, G-Series Entities, and Asset Vehicles',
    shortTitle: '关联人/公司线',
    court: 'Multi-forum',
    docket: 'Cross-case watchlist',
    kind: 'Entity Intelligence',
    status: 'Ongoing entity and docket correlation',
    priority: 'high',
    lastKnownFiling: 'Continuous monitoring',
    stage: 'Tracks GTV, Saraca, Voice of Guo, G Clubs, Himalaya Exchange, Farm Loan, Rule of Law entities, family/trust/fund references.',
    focus: 'Related defendants, promoters, entity defendants, third-party claimants, assets, alleged victims, and source reliability.',
    sourceIds: ['doj-victim-page', 'sec-press-2023-50', 'gtv-fair-fund', 'epiq-kwok-trustee'],
    watchQuestions: [
      'Whether new filings identify previously unknown nominee, family, trust, foundation, or offshore-entity relationships.',
      'Whether G-series investor petitions create a coordinated ancillary proceeding or separate appellate activity.',
    ],
  },
]

export const entities = [
  {
    id: 'ho-wan-kwok',
    name: 'Ho Wan Kwok / Miles Guo / 郭文贵',
    type: 'Person',
    role: 'Defendant, debtor, central subject',
    caseIds: ['sdny-23-cr-118', 'ca2-26-1853', 'ca2-26-563-dx', 'sdny-23-cv-2200', 'dconn-22-50073', 'bkd-22-05032', 'dconn-26-withdrawal-reference', 'ca2-24-2504', 'edny-26-mc-2795'],
    riskAreas: ['Criminal appeal', 'Forfeiture', 'Bankruptcy estate', 'SEC civil enforcement'],
    notes: 'Convicted on nine counts in the criminal case; judgment entered July 2, 2026 according to mirrored docket material.',
  },
  {
    id: 'kin-ming-je',
    name: 'Kin Ming Je / William Je',
    type: 'Person',
    role: 'Co-defendant and financial adviser alleged by DOJ/SEC',
    caseIds: ['sdny-23-cr-118', 'sdny-23-cv-2200'],
    riskAreas: ['At-large status', 'SEC enforcement', 'Asset tracing'],
    notes: 'DOJ victim page names him as a defendant; latest live status should be confirmed against official sources.',
  },
  {
    id: 'yanping-wang',
    name: 'Yanping Wang / Yvette Wang',
    type: 'Person',
    role: 'Co-defendant who pleaded guilty and was sentenced',
    caseIds: ['sdny-23-cr-118'],
    riskAreas: ['Forfeiture', 'Cooperation / sentencing record', 'Related mandamus petitions'],
    notes: 'DOJ victim page reports plea and sentencing information; track forfeiture orders and third-party petitions involving her case caption.',
  },
  {
    id: 'gtv-media',
    name: 'GTV Media Group',
    type: 'Company',
    role: 'G-series / SEC Fair Fund entity',
    caseIds: ['sdny-23-cv-2200', 'sec-admin-3-20537', 'sdny-23-cr-118', 'az-voice-of-guo'],
    riskAreas: ['Investor claims', 'SEC distribution', 'Criminal forfeiture offset'],
    notes: 'Fair Fund and SEC proceedings are central to the $411M offset credited in the criminal forfeiture ruling.',
  },
  {
    id: 'saraca-media',
    name: 'Saraca Media Group',
    type: 'Company',
    role: 'SEC Fair Fund entity',
    caseIds: ['sdny-23-cv-2200', 'sec-admin-3-20537', 'az-voice-of-guo'],
    riskAreas: ['Investor claims', 'SEC distribution'],
    notes: 'Named on the GTV Media Group Fair Fund site.',
  },
  {
    id: 'voice-of-guo',
    name: 'Voice of Guo Media',
    type: 'Company',
    role: 'SEC Fair Fund entity',
    caseIds: ['sdny-23-cv-2200', 'sec-admin-3-20537', 'az-voice-of-guo'],
    riskAreas: ['Investor claims', 'SEC distribution'],
    notes: 'Named on the GTV Media Group Fair Fund site.',
  },
  {
    id: 'hk-international',
    name: 'HK International Funds Investments',
    type: 'Company / Asset Vehicle',
    role: 'Asset-ownership and alter ego line',
    caseIds: ['dconn-22-50073', 'bkd-hk-int-despins', 'ca2-24-2504'],
    riskAreas: ['Alter ego', 'Bankruptcy estate property', 'Lady May asset line'],
    notes: 'Treat family, fund, and trust assertions as source-dependent until verified in court filings.',
  },
  {
    id: 'rule-of-law-entities',
    name: 'Rule of Law Foundation / Rule of Law Society line',
    type: 'Nonprofit / Entity Line',
    role: 'Related organization watchlist',
    caseIds: ['related-people-companies', 'az-voice-of-guo'],
    riskAreas: ['Entity relationships', 'Donor / investor claims', 'Source verification'],
    notes: 'Included for relationship mapping; only court-filed or official-agency facts should be treated as proven.',
  },
  {
    id: 'himalaya-exchange',
    name: 'Himalaya Exchange / H-Coin / H-Dollar line',
    type: 'Digital Asset / Entity Line',
    role: 'G-series related offering watchlist',
    caseIds: ['sdny-23-cr-118', 'sdny-23-cv-2200', 'related-people-companies'],
    riskAreas: ['Digital asset claims', 'Investor losses', 'Forfeiture remission'],
    notes: 'Track alongside GTV, G Clubs, Farm Loan, and related investor petitions.',
  },
  {
    id: 'lamp-capital',
    name: 'Lamp Capital LLC',
    type: 'Company / Asset Vehicle',
    role: 'Defendant and related entity in trustee estate-recovery litigation',
    caseIds: ['dconn-22-50073', 'bkd-24-05275-lamp'],
    riskAreas: ['Bankruptcy estate recovery', 'Entity relationships', 'Asset ownership'],
    notes: 'Relationship and liability conclusions must be tied to filed pleadings and court rulings in adversary proceeding 24-05275.',
  },
]

export const seedEvents = [
  {
    id: 'sdny-23-cr-118-doc-868',
    date: '2026-08-06',
    title: 'Doc 868: Second Circuit mandate denies tandem pro se mandamus petitions',
    summary: 'The mirrored docket summary says the Second Circuit denied tandem pro se mandamus petitions, while leaving denial as to docketing and consideration of third-party forfeiture claims without prejudice to renewal.',
    impact: 'This keeps pressure on the district court over third-party forfeiture claims but does not yet create relief for claimants.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118'],
    court: 'S.D.N.Y. / Second Circuit',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: '868',
    category: 'Mandamus',
    severity: 'high',
    sourceId: 'nfsc-criminal-mirror',
    sourceLabel: 'NFSC mirror of court filing',
    sourceType: 'Mirror',
    sourceUrl: 'https://nfsc.press/wp-content/uploads/2024/08/868.0.pdf',
    confidence: 'medium',
    assertionType: 'Mirror summary of court filing',
    entities: ['ho-wan-kwok'],
    tags: ['forfeiture', 'third-party claims', 'mandamus', 'Second Circuit'],
  },
  {
    id: 'sdny-23-cr-118-doc-867',
    date: '2026-08-03',
    title: 'Doc 867: Pro se third-party mandamus petition seeks vacatur, hearing, and stay',
    summary: 'A third-party pro se petition reportedly sought vacatur of conviction, sentencing, and forfeiture orders, an evidentiary hearing on the government victim list, and a stay of forfeiture proceedings.',
    impact: 'The filing indicates continuing organized resistance from alleged investors or third-party claimants, but its legal effect depends on appellate action and proper docketing.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118'],
    court: 'S.D.N.Y. / Second Circuit',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: '867',
    category: 'Mandamus',
    severity: 'medium',
    sourceId: 'nfsc-criminal-mirror',
    sourceLabel: 'NFSC mirror of court filing',
    sourceType: 'Mirror',
    sourceUrl: 'https://nfsc.press/wp-content/uploads/2024/08/867.pdf',
    confidence: 'medium',
    assertionType: 'Third-party pro se claim',
    entities: ['ho-wan-kwok'],
    tags: ['third-party claims', 'forfeiture', 'victim list', 'stay request'],
  },
  {
    id: 'sdny-23-cr-118-doc-866',
    date: '2026-07-30',
    title: 'Doc 866: Limited unsealing order for § 853 ancillary petitions',
    summary: 'The court granted limited unsealing solely so the government could obtain unredacted copies of § 853 ancillary petitions from the Clerk.',
    impact: 'This suggests the ancillary forfeiture process is procedurally active, while public access and privacy redactions remain controlled.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118'],
    court: 'S.D.N.Y.',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: '866',
    category: 'Forfeiture',
    severity: 'high',
    sourceId: 'nfsc-criminal-mirror',
    sourceLabel: 'NFSC mirror of court filing',
    sourceType: 'Mirror',
    sourceUrl: 'https://nfsc.press/wp-content/uploads/2024/08/866.pdf',
    confidence: 'medium',
    assertionType: 'Court order',
    entities: ['ho-wan-kwok'],
    tags: ['853(n)', 'ancillary proceeding', 'unsealing', 'forfeiture'],
  },
  {
    id: 'sdny-23-cr-118-doc-864',
    date: '2026-07-15',
    title: 'Doc 864: Sentencing transcript posted',
    summary: 'The mirrored docket says the sentencing transcript records a 360-month sentence, below the 2100-month Guidelines range, an $889M forfeiture money judgment, denial of a Fatico hearing, and a loss finding above $550M.',
    impact: 'The transcript is key evidence for appellate issues, forfeiture rationale, loss calculation, restitution impracticability, and mitigation arguments.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118'],
    court: 'S.D.N.Y.',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: '864',
    category: 'Sentencing',
    severity: 'critical',
    sourceId: 'nfsc-criminal-mirror',
    sourceLabel: 'NFSC mirror of court filing',
    sourceType: 'Mirror',
    sourceUrl: 'https://nfsc.press/wp-content/uploads/2024/08/864.pdf',
    confidence: 'medium',
    assertionType: 'Transcript',
    entities: ['ho-wan-kwok'],
    tags: ['sentencing', 'forfeiture', 'Fatico', 'loss calculation'],
  },
  {
    id: 'sdny-23-cr-118-doc-862',
    date: '2026-07-02',
    title: 'Doc 862: Notice of appeal filed',
    summary: 'Miles Guo filed a notice of appeal to the Second Circuit from the July 2, 2026 judgment, appealing the conviction and sentence.',
    impact: 'The direct appeal becomes the controlling forward-looking litigation track; the next critical items are appellate docket number, counsel, transcripts, and briefing schedule.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118'],
    court: 'S.D.N.Y. / Second Circuit',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: '862',
    category: 'Appeal',
    severity: 'critical',
    sourceId: 'nfsc-criminal-mirror',
    sourceLabel: 'NFSC mirror of court filing',
    sourceType: 'Mirror',
    sourceUrl: 'https://nfsc.press/wp-content/uploads/2024/08/862.pdf',
    confidence: 'medium',
    assertionType: 'Court filing',
    entities: ['ho-wan-kwok'],
    tags: ['appeal', 'Second Circuit', 'judgment'],
  },
  {
    id: 'sdny-23-cr-118-doc-860',
    date: '2026-07-02',
    title: 'Doc 860: Judgment entered against Miles Guo',
    summary: 'The judgment reportedly imposes 360 months of imprisonment, a $900 special assessment, no supervised release, and an $889M forfeiture money judgment after conviction on nine counts and acquittal on three counts.',
    impact: 'This is the final criminal judgment that triggers appeal deadlines and frames post-conviction, forfeiture, and victim remission activity.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118'],
    court: 'S.D.N.Y.',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: '860',
    category: 'Judgment',
    severity: 'critical',
    sourceId: 'nfsc-criminal-mirror',
    sourceLabel: 'NFSC mirror of court filing',
    sourceType: 'Mirror',
    sourceUrl: 'https://nfsc.press/wp-content/uploads/2024/08/860.pdf',
    confidence: 'medium',
    assertionType: 'Court judgment',
    entities: ['ho-wan-kwok'],
    tags: ['judgment', 'sentence', 'forfeiture', 'appeal deadline'],
  },
  {
    id: 'sdny-23-cr-118-doc-859',
    date: '2026-06-30',
    title: 'Doc 859: Supplemental preliminary forfeiture order adds bank accounts',
    summary: 'The court reportedly ordered forfeiture of additional assets, including a Banco Popular account of about $2.11M and four Barclays accounts under aliases, with third-party claim notice through forfeiture.gov.',
    impact: 'Asset-specific forfeiture expands beyond the money judgment and creates deadlines for third-party interests.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118'],
    court: 'S.D.N.Y.',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: '859',
    category: 'Forfeiture',
    severity: 'high',
    sourceId: 'nfsc-criminal-mirror',
    sourceLabel: 'NFSC mirror of court filing',
    sourceType: 'Mirror',
    sourceUrl: 'https://nfsc.press/wp-content/uploads/2024/08/859.pdf',
    confidence: 'medium',
    assertionType: 'Court order',
    entities: ['ho-wan-kwok'],
    tags: ['asset forfeiture', 'Banco Popular', 'Barclays', 'third-party notice'],
  },
  {
    id: 'sdny-23-cr-118-doc-858',
    date: '2026-06-29',
    title: 'Doc 858: Forfeiture money judgment reduced from $1.3B to $889M',
    summary: 'The court reportedly sustained Guo forfeiture objections in part, credited $411M disgorged through the SEC/GTV line, denied a motion to compel seizure of bankruptcy assets, and authorized victim remission in lieu of restitution.',
    impact: 'This links the criminal case, SEC Fair Fund, and bankruptcy estate. It is one of the most important cross-forum rulings for asset recovery.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118', 'sdny-23-cv-2200', 'sec-admin-3-20537', 'dconn-22-50073'],
    court: 'S.D.N.Y.',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: '858',
    category: 'Forfeiture',
    severity: 'critical',
    sourceId: 'nfsc-criminal-mirror',
    sourceLabel: 'NFSC mirror of court filing',
    sourceType: 'Mirror',
    sourceUrl: 'https://nfsc.press/wp-content/uploads/2024/08/858.pdf',
    confidence: 'medium',
    assertionType: 'Court order',
    entities: ['ho-wan-kwok', 'gtv-media'],
    tags: ['forfeiture', 'SEC offset', 'bankruptcy assets', 'remission', 'restitution'],
  },
  {
    id: 'ca2-24-2504-opinion-2026-04-06',
    date: '2026-04-06',
    title: 'Second Circuit reported decision in In re Kwok, 172 F.4th 145',
    summary: 'The appellate line concerns whether assets nominally connected to HK International Funds Investments and the Lady May asset line are property of the Kwok bankruptcy estate under alter ego analysis.',
    impact: 'The ruling is central to the family, nominee, and asset-vehicle map because it can pull nominally separate assets into the bankruptcy estate.',
    caseId: 'ca2-24-2504',
    relatedCaseIds: ['dconn-22-50073', 'ca2-24-2504'],
    court: 'Second Circuit',
    docketNumber: '24-2504',
    filingNumber: '172 F.4th 145',
    category: 'Bankruptcy Appeal',
    severity: 'high',
    sourceId: 'courtlistener-recap',
    sourceLabel: 'CourtListener / appellate reporter reference',
    sourceType: 'CourtListener / RECAP',
    sourceUrl: 'https://www.courtlistener.com/',
    confidence: 'medium',
    assertionType: 'Reported appellate decision reference',
    entities: ['ho-wan-kwok', 'hk-international'],
    tags: ['bankruptcy', 'alter ego', 'Lady May', 'HK International', 'estate property'],
  },
  {
    id: 'sdny-23-cr-118-yvette-sentencing-2025-01-06',
    date: '2025-01-06',
    title: 'Yanping Wang / Yvette Wang sentenced to 120 months according to DOJ victim page',
    summary: 'The DOJ victim information page reports that Yanping Wang pleaded guilty and was sentenced to 120 months with forfeiture exposure tied to the broader case.',
    impact: 'Wang-related forfeiture and claimant petitions need to be tracked separately from Guo direct appeal issues.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118'],
    court: 'S.D.N.Y.',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: 'DOJ victim update',
    category: 'Sentencing',
    severity: 'high',
    sourceId: 'doj-victim-page',
    sourceLabel: 'DOJ victim information page',
    sourceType: 'Official Agency',
    sourceUrl: 'https://www.justice.gov/usao-sdny/united-states-v-ho-wan-kwok-aka-miles-guo-and-kin-ming-je-aka-william-je',
    confidence: 'high',
    assertionType: 'Official agency statement',
    entities: ['yanping-wang'],
    tags: ['Yvette Wang', 'sentencing', 'forfeiture'],
  },
  {
    id: 'sdny-23-cr-118-verdict-2024-07-16',
    date: '2024-07-16',
    title: 'Jury convicts Miles Guo on fraud, racketeering, securities fraud, and money-laundering counts',
    summary: 'The criminal conviction supplies the predicate for sentencing, forfeiture, appeal, and victim remission tracks.',
    impact: 'Appellate strategy will likely attack trial rulings, sufficiency, evidentiary issues, loss, and forfeiture.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118', 'sdny-23-cv-2200'],
    court: 'S.D.N.Y.',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: 'Verdict',
    category: 'Trial',
    severity: 'critical',
    sourceId: 'doj-victim-page',
    sourceLabel: 'DOJ victim information page',
    sourceType: 'Official Agency',
    sourceUrl: 'https://www.justice.gov/usao-sdny/united-states-v-ho-wan-kwok-aka-miles-guo-and-kin-ming-je-aka-william-je',
    confidence: 'high',
    assertionType: 'Official agency statement',
    entities: ['ho-wan-kwok'],
    tags: ['conviction', 'trial', 'forfeiture predicate'],
  },
  {
    id: 'gtv-fair-fund-second-tranche-2023-09-29',
    date: '2023-09-29',
    title: 'GTV Fair Fund second tranche distribution commenced',
    summary: 'The GTV Fair Fund site states that second tranche distribution began on September 29, 2023 and payments are ongoing under the approved plan.',
    impact: 'Fair Fund distributions matter because criminal forfeiture rulings credited SEC/GTV disgorgement against the criminal money judgment.',
    caseId: 'sec-admin-3-20537',
    relatedCaseIds: ['sec-admin-3-20537', 'sdny-23-cr-118', 'sdny-23-cv-2200'],
    court: 'SEC Administrative Proceeding',
    docketNumber: '3-20537',
    filingNumber: 'Fair Fund update',
    category: 'Fair Fund',
    severity: 'high',
    sourceId: 'gtv-fair-fund',
    sourceLabel: 'GTV Media Group Fair Fund',
    sourceType: 'Claims Agent',
    sourceUrl: 'https://www.gtvmediagroupfairfund.com/',
    confidence: 'high',
    assertionType: 'Claims administrator statement',
    entities: ['gtv-media', 'saraca-media', 'voice-of-guo'],
    tags: ['Fair Fund', 'SEC', 'distribution', 'offset'],
  },
  {
    id: 'sec-press-2023-50',
    date: '2023-03-15',
    title: 'SEC announces civil charges against Miles Guo and William Je',
    summary: 'The SEC announced charges alleging an $850M fraud scheme involving GTV and related offerings.',
    impact: 'The civil allegations and Fair Fund mechanics form a separate but overlapping investor-recovery track from criminal forfeiture.',
    caseId: 'sdny-23-cv-2200',
    relatedCaseIds: ['sdny-23-cv-2200', 'sec-admin-3-20537', 'sdny-23-cr-118'],
    court: 'SEC / S.D.N.Y.',
    docketNumber: '1:23-cv-02200',
    filingNumber: 'SEC 2023-50',
    category: 'Civil Enforcement',
    severity: 'high',
    sourceId: 'sec-press-2023-50',
    sourceLabel: 'SEC press release',
    sourceType: 'Official Agency',
    sourceUrl: 'https://www.sec.gov/newsroom/press-releases/2023-50',
    confidence: 'high',
    assertionType: 'Official agency allegation',
    entities: ['ho-wan-kwok', 'kin-ming-je', 'gtv-media'],
    tags: ['SEC', 'GTV', 'securities fraud', 'civil enforcement'],
  },
  {
    id: 'sdny-23-cr-118-indictment-2023-03-15',
    date: '2023-03-15',
    title: 'Federal criminal case filed against Miles Guo and Kin Ming Je',
    summary: 'The DOJ victim page identifies the federal criminal case against Ho Wan Kwok, Kin Ming Je, and Yanping Wang, with fraud, racketeering, securities, and money-laundering tracks.',
    impact: 'This is the origin point for the criminal docket, related forfeiture, victim notice, and later appellate proceedings.',
    caseId: 'sdny-23-cr-118',
    relatedCaseIds: ['sdny-23-cr-118', 'sdny-23-cv-2200'],
    court: 'S.D.N.Y.',
    docketNumber: '1:23-cr-00118-AT',
    filingNumber: 'Indictment / DOJ victim page',
    category: 'Indictment',
    severity: 'critical',
    sourceId: 'doj-victim-page',
    sourceLabel: 'DOJ victim information page',
    sourceType: 'Official Agency',
    sourceUrl: 'https://www.justice.gov/usao-sdny/united-states-v-ho-wan-kwok-aka-miles-guo-and-kin-ming-je-aka-william-je',
    confidence: 'high',
    assertionType: 'Official agency statement',
    entities: ['ho-wan-kwok', 'kin-ming-je', 'yanping-wang'],
    tags: ['indictment', 'victim notice', 'criminal case'],
  },
  {
    id: 'dconn-22-50073-bankruptcy-filed-2022-02-15',
    date: '2022-02-15',
    title: 'Ho Wan Kwok bankruptcy case begins in D. Conn.',
    summary: 'The bankruptcy case creates an estate-administration track for assets and creditor claims that later intersects with criminal forfeiture and Second Circuit alter ego rulings.',
    impact: 'Any program tracking the Guo matter must correlate criminal forfeiture against bankruptcy estate control and trustee recovery.',
    caseId: 'dconn-22-50073',
    relatedCaseIds: ['dconn-22-50073', 'sdny-23-cr-118', 'ca2-24-2504'],
    court: 'D. Conn. Bankruptcy Court',
    docketNumber: '22-50073',
    filingNumber: 'Petition',
    category: 'Bankruptcy',
    severity: 'high',
    sourceId: 'epiq-kwok-trustee',
    sourceLabel: 'Epiq Kwok Trustee case page',
    sourceType: 'Claims Agent',
    sourceUrl: 'https://dm.epiq11.com/case/kwoktrustee/dockets',
    confidence: 'medium',
    assertionType: 'Case docket reference',
    entities: ['ho-wan-kwok'],
    tags: ['bankruptcy', 'estate', 'trustee', 'asset recovery'],
  },
]

export const policyWatch = [
  {
    id: 'criminal-forfeiture-remission',
    title: 'Criminal forfeiture, third-party interests, and remission',
    area: 'DOJ / Federal Criminal Procedure',
    relevance: 'The Guo matter puts the $889M forfeiture judgment, § 853(n) ancillary petitions, victim remission, and no-restitution finding on this policy line.',
    monitorTerms: ['criminal forfeiture remission', '21 U.S.C. 853(n)', 'restoration remission victims'],
    sourceIds: ['pacer', 'federal-register-policy', 'doj-victim-page'],
    posture: 'High impact; monitor court orders before policy commentary.',
  },
  {
    id: 'sec-fair-fund',
    title: 'SEC Fair Funds and digital-asset or securities-offering enforcement',
    area: 'SEC Enforcement',
    relevance: 'GTV Fair Fund payments affect criminal-forfeiture offsets and investor recovery.',
    monitorTerms: ['SEC Fair Fund digital asset offering', 'GTV Media Group Fair Fund', 'disgorgement investor distribution'],
    sourceIds: ['sec-press-2023-50', 'gtv-fair-fund', 'federal-register-policy'],
    posture: 'Cross-forum offset issue; separate agency allegation from court finding.',
  },
  {
    id: 'bankruptcy-asset-recovery',
    title: 'Bankruptcy estate, alter ego, and nominee asset recovery',
    area: 'Bankruptcy / Appellate',
    relevance: 'HK International, Lady May, and family, fund, or trust asset claims must be verified through bankruptcy docket and appellate records.',
    monitorTerms: ['alter ego bankruptcy estate asset recovery', 'nominee ownership bankruptcy', 'Ho Wan Kwok trustee'],
    sourceIds: ['epiq-kwok-trustee', 'courtlistener-recap', 'pacer'],
    posture: 'Do not treat family/foundation allegations as facts until tied to filings.',
  },
  {
    id: 'china-transnational-context',
    title: 'China-linked transnational politics, sanctions, and foreign-influence narratives',
    area: 'Policy Context',
    relevance: 'Whistleblower Movement narratives and related political claims can shape media interpretation and supporter behavior, but they do not replace court records.',
    monitorTerms: ['transnational repression China policy', 'foreign influence enforcement China', 'political asylum fraud case context'],
    sourceIds: ['federal-register-policy'],
    posture: 'Context only unless an official filing directly cites it.',
  },
]

export const initialSourceStatuses = sourceRegistry.map((source) => ({
  sourceId: source.id,
  status: source.enabled ? 'not_run' : 'disabled',
  checkedAt: null,
  latencyMs: null,
  itemCount: 0,
  message: source.enabled ? 'Ready for refresh.' : 'Disabled.',
  facts: [],
}))

export function createSeedState() {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    cases,
    entities,
    events: seedEvents,
    sources: sourceRegistry,
    sourceStatuses: initialSourceStatuses,
    policyWatch,
    notes: [
      'Official court dockets require PACER credentials for authoritative latest-state verification.',
      'NFSC is used only as a public PDF mirror, not as an adjudicative source.',
      'Family, trust, foundation, and nominee-ownership references must be tied to filings before being promoted from watchlist to fact.',
    ],
  }
}
